name:                portfolio-tracker
version:             0.1.0.0
github:              "mprushin/portfolio-tracker"
license:             BSD3
author:              "Mikhail Prushinskiy <mprushinsky@gmail.com>"
maintainer:          "Mikhail Prushinskiy <mprushinsky@gmail.com>"
copyright:           "2022 Mprushin <mprushinsky@gmail.com>"
synopsis:            Anonymous portfolio tracker
description:         You can find documentation at
homepage:            https://github.com/mprushin/portfolio-tracker
category:            Bitcoin

extra-source-files:
- README.md

default-extensions:
  - NoImplicitPrelude
  #- MultiParamTypeClasses
  #- LambdaCase
  - OverloadedStrings
  #- ScopedTypeVariables
         #- DeriveGeneric
    #- GADTs
  - GeneralizedNewtypeDeriving
    #- TupleSections
         #- DataKinds
  - DerivingStrategies
    #- KindSignatures
    #- FlexibleContexts
    #- FlexibleInstances
    #- StrictData
    #- TypeFamilies
    #- TypeOperators
    #- StandaloneDeriving
    #- DeriveLift
    #- DerivingVia
    #- ExistentialQuantification
    #- InstanceSigs
    #- AllowAmbiguousTypes

ghc-options:
  #  - -Weverything
  - -Werror
  - -Wno-missing-exported-signatures # missing-exported-signatures turns off the more strict -Wmissing-signatures. See https://ghc.haskell.org/trac/ghc/ticket/14794#ticket
  - -Wno-missing-import-lists # Requires explicit imports of _every_ function (e.g. ‘$’); too strict
  - -Wno-missed-specialisations # When GHC can’t specialize a polymorphic function. No big deal and requires fixing underlying libraries to solve.
  - -Wno-all-missed-specialisations # See missed-specialisations
  - -Wno-unsafe # Don’t use Safe Haskell warnings
  - -Wno-safe # Don’t use Safe Haskell warnings
  - -Wno-missing-local-signatures # Warning for polymorphic local bindings; nothing wrong with those.
  - -Wno-missing-safe-haskell-mode
  - -Wno-prepositive-qualified-module
  - -fenable-th-splice-warnings
  - -fprint-potential-instances
  #ghc-options:
# For details on warnings: https://downloads.haskell.org/~ghc/master/users-guide/using-warnings.html
# Enable all warnings with -Weverything, then disable the ones we don’t care about
#- -Weverything
#- -Werror
#- -Wno-missing-exported-signatures # missing-exported-signatures turns off the more strict -Wmissing-signatures. See https://ghc.haskell.org/trac/ghc/ticket/14794#ticket
#- -Wno-missing-import-lists # Requires explicit imports of _every_ function (e.g. ‘$’); too strict
#- -Wno-missed-specialisations # When GHC can’t specialize a polymorphic function. No big deal and requires fixing underlying libraries to solve.
#- -Wno-all-missed-specialisations # See missed-specialisations
#- -Wno-unsafe # Don’t use Safe Haskell warnings
#- -Wno-safe # Don’t use Safe Haskell warnings
#- -Wno-missing-local-signatures # Warning for polymorphic local bindings; nothing wrong with those.
#- -Wno-missing-safe-haskell-mode
#- -Wno-prepositive-qualified-module
#- -fenable-th-splice-warnings
#- -fprint-potential-instances

#library:
#  source-dirs:
#  - src
#  ghc-options:
#  - -fwarn-tabs
#  dependencies:
#  - base ^>=4.15.1.0
#  - bytestring
#  - text
#  - http2
#  - network-run

executables:
  portfolio-tracker-exe:
    main: Main.hs
    dependencies:
    - base ^>=4.15.1.0
    - bytestring
    - http-types
    - text
    - http2
    - network-run
    source-dirs:
    - app
    - src
      #    ghc-options:
      #    - -O2
      #    - -optc-O3
      #    - -funfolding-use-threshold=16
      #    - -threaded
      #    - -rtsopts
      #    - -with-rtsopts=-N
      #    - -optl-fuse-ld=gold
      #    ld-options:
      #    - -fuse-ld=gold

